name: rtdp
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.3=h50f4ffc_4
  - libcxx=20.1.8=hd7fd590_1
  - libexpat=2.7.3=h50f4ffc_4
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.18=h9b4081a_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.9.0=py311hca03da5_0
  - sqlite=3.51.0=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - contourpy==1.3.3
      - cycler==0.12.1
      - fonttools==4.61.0
      - idna==3.11
      - kiwisolver==1.4.9
      - matplotlib==3.10.7
      - numpy==2.3.5
      - packaging==25.0
      - pillow==12.0.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - requests==2.32.5
      - six==1.17.0
      - urllib3==2.6.1
